version: 2
project_name: buyqcloud

builds:
  - id: buyqcloud
    binary: buyqcloud
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - solaris
      - js
      - wasip1
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - loong64
      - mips64
      - ppc64
      - riscv64
      - s390x
      - mips
      - wasm
    ldflags:
      - -s -w --extldflags "-static"

upx:
  - enabled: true
    # Filter by build ID.
    ids:
      - buyqcloud
    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best
    # Whether to try LZMA (slower).
    lzma: true
    # Whether to try all methods and filters (slow).
    brute: false

archives:
  - id: buyqcloud
    ids:
      - buyqcloud
    formats: ["zip"]
    wrap_in_directory: false
    strip_binary_directory: true
    files:
      - LICENSE
