version: 2
project_name: buyqcloud

builds:
  - id: buyqcloud
    binary: buyqcloud
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - solaris
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - loong64
      - mips64
      - ppc64
      - riscv64
      - s390x
      - mips
    ldflags:
      - -s -w --extldflags "-static"

archives:
  - id: buyqcloud
    ids:
      - buyqcloud
    formats: ["zip"]
    wrap_in_directory: false
    strip_binary_directory: true
    files:
      - LICENSE
